"""empty message

Revision ID: 9dcf1d5c4847
Revises: 
Create Date: 2020-05-19 18:52:23.502796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9dcf1d5c4847'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('meal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ingredients', 'meals', ['meal_id'], ['id'])
    op.drop_column('meals', 'ingredients')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meals', sa.Column('ingredients', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'ingredients', type_='foreignkey')
    op.drop_column('ingredients', 'meal_id')
    # ### end Alembic commands ###
